version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: "host=db user=postgres password=postgres database=avito"
    depends_on:
      - db

  db:
    restart: always
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=avito
    volumes:
      - db-data:/var/lib/postgresql/data
  

volumes:
  db-data:
